export const WORDS = [
  "airplane",
  "anchor",
  "angel",
  "apple",
  "backpack",
  "balloon",
  "banana",
  "basketball",
  "beach",
  "bear",
  "bicycle",
  "bird",
  "birthday cake",
  "book",
  "bridge",
  "butterfly",
  "camera",
  "campfire",
  "candle",
  "castle",
  "cat",
  "caterpillar",
  "chair",
  "cheese",
  "chicken",
  "clock",
  "cloud",
  "computer",
  "crown",
  "dinosaur",
  "dog",
  "dolphin",
  "door",
  "dragon",
  "drum",
  "elephant",
  "envelope",
  "eye",
  "feather",
  "fire truck",
  "fireworks",
  "fish",
  "flag",
  "flower",
  "football",
  "forest",
  "fork",
  "fountain",
  "frog",
  "ghost",
  "giraffe",
  "glasses",
  "globe",
  "guitar",
  "hamburger",
  "hammer",
  "helicopter",
  "horse",
  "house",
  "ice cream",
  "igloo",
  "island",
  "jacket",
  "jellyfish",
  "key",
  "kite",
  "ladder",
  "lamp",
  "lighthouse",
  "lightning",
  "lion",
  "lock",
  "magnet",
  "mailbox",
  "map",
  "mermaid",
  "microphone",
  "moon",
  "mountain",
  "mushroom",
  "necklace",
  "octopus",
  "orange",
  "owl",
  "paintbrush",
  "palm tree",
  "panda",
  "paper airplane",
  "parachute",
  "penguin",
  "piano",
  "pizza",
  "pumpkin",
  "puzzle",
  "rainbow",
  "robot",
  "rocket",
  "roller coaster",
  "sailboat",
  "sandcastle",
  "scarecrow",
  "scissors",
  "shark",
  "sheep",
  "ship",
  "shoes",
  "skeleton",
  "skateboard",
  "snowman",
  "soccer ball",
  "spaceship",
  "spider",
  "starfish",
  "stop sign",
  "sunflower",
  "sunglasses",
  "sword",
  "telescope",
  "tent",
  "tiger",
  "toothbrush",
  "tornado",
  "tractor",
  "train",
  "treehouse",
  "treasure chest",
  "turtle",
  "umbrella",
  "unicorn",
  "volcano",
  "waterfall",
  "watermelon",
  "whale",
  "windmill",
  "window",
  "xylophone",
  "yacht",
  "yo-yo",
  "zebra",
] as const;

// Add alternatives only when we want to accept a different name for a word.
const ACCEPTED_ANSWERS: Record<string, readonly string[]> = {
  airplane: ["plane", "aeroplane"],
  basketball: ["basket ball"],
  bicycle: ["bike"],
  birthdaycake: ["birthday cake"],
  firetruck: ["fire truck", "fire engine"],
  football: ["soccer", "soccer ball"],
  hamburger: ["burger"],
  icecream: ["ice cream"],
  microphone: ["mic"],
  paperairplane: ["paper plane"],
  "yo-yo": ["yoyo"],
};

function normalizeAnswer(answer: string): string {
  return answer.trim().toLowerCase().replace(/\s+/g, " ");
}

export function isAcceptedAnswer(word: string, guess: string): boolean {
  const normalizedWord = normalizeAnswer(word);
  const normalizedGuess = normalizeAnswer(guess);

  return (
    normalizedGuess === normalizedWord ||
    (ACCEPTED_ANSWERS[normalizedWord.replace(/\s/g, "")] ?? []).some(
      (answer) => normalizeAnswer(answer) === normalizedGuess,
    )
  );
}
